# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
image:
  file: .gitpod.Dockerfile

tasks:
  - init: npm install && npm run build && ./gradlew build
    command: npm run start

vscode:
  extensions:
    - vscjava.vscode-java-pack

