services:
  postgres:
    image: postgres:16.4-alpine
    container_name: postgres
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    environment:
    - POSTGRES_DB=mfApp
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=P4ssword!
    ports:
    - 5433:5432

  redis:
    image: 'redis:7.2.5-alpine'
    container_name: redis
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    ports:
      - '127.0.0.1:6379:6379/tcp'
    volumes:
      - 'redis_data:/data:rw'
    healthcheck:
      test: redis-cli ping
      interval: 3s
      timeout: 5s
      retries: 5

volumes:
  redis_data:
